"""
Django settings for final_topic project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
LINE_CHANNEL_ACCESS_TOKEN = '5bMjuXBe1Uz+ceO2ZEQ4hxwVpndIzOU2N1GOAm/QaZPQRoL0KZu7eXv/b8xJ0Gd8PZfrdMsSfZe4uxssV09TeyzhjNzR2JjMRg9cTfSBnymrVwdF0PW0Vdjo7dhSLxR6mSNwhTt8XbMIWSCWYY6ijwdB04t89/1O/w1cDnyilFU='
 
LINE_CHANNEL_SECRET = '297efe8ecccf805cd3981ce1b2d25cdb'

from ntpath import join
from os import path
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$q$%+)%@r^m^)di_u$h$(b9kh071m5ue5wzcgn+r77c3xaj%@m'

# SECURITY WARNING: don't run with debug turned on in production!
#除錯模式 開啟  部屬時建議關掉
DEBUG = True

# ALLOWED_HOSTS = [
#     'bc0b-118-170-47-201.ngrok.io'
#      # 允許的網域名稱  ngrok裡的第2個Forwarding
# ]
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'mylinebot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'final_topic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'final_topic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hant'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#-----------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# 第1種寫法
STATICFILES_DIRS=[ os.path.join(BASE_DIR, 'static'), ]

# 第2種寫法
# PROJECT_PATH = os.path.abspath(os.path.dirname(__file__))
# STATIC_ROOT = os.path.join(os.path.dirname(PROJECT_PATH), 'static')
# STATICFILES_DIRS = (
#     ("css", os.path.join(STATIC_ROOT, 'css')),
#     ("js", os.path.join(STATIC_ROOT, 'js')),
#     ("img", os.path.join(STATIC_ROOT, 'img')),
# )

#-----------------------------------------------------------------------------

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
